version: "2"

networks:
  fabric_test:
    external: true

services:
  ccapi.org1.example.com:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
    volumes:
      - ./:/rest-server
      - /src/github.com/hyperledger/fabric-private-chaincode/samples/deployment/test-network/fabric-samples/test-network/organizations:/fabric/organizations
    logging:
      options:
        max-size: 50m  
    environment:
      - SDK_PATH=./config/configsdk-org1.yaml
      - USER=Admin
      - ORG=org1
      - DOMAIN=example.com
      - CHANNEL=mychannel
      - CCNAME=cc-tools-demo
      - FABRIC_GATEWAY_ENDPOINT=peer0.org1.example.com:7051
      - FABRIC_GATEWAY_NAME=peer0.org1.example.com
      - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn
    working_dir: /rest-server
    container_name: ccapi.org1.example.com
    networks:
      - fabric_test
  ccapi.org2.example.com:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 980:80
    volumes:
      - ./:/rest-server
      - /src/github.com/hyperledger/fabric-private-chaincode/samples/deployment/test-network/fabric-samples/test-network/organizations:/fabric/organizations
    logging:
      options:
        max-size: 50m  
    environment:
      - SDK_PATH=./config/configsdk-org2.yaml
      - USER=Admin
      - ORG=org2
      - DOMAIN=example.com
      - CHANNEL=mychannel
      - CCNAME=cc-tools-demo
      - FABRIC_GATEWAY_ENDPOINT=peer0.org2.example.com:7051
      - FABRIC_GATEWAY_NAME=peer0.org2.example.com
      - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn
    working_dir: /rest-server
    container_name: ccapi.org2.example.com
    networks:
      - fabric_test
