version: "2"

networks:
  cc-tools-demo-net:
    external: true

services:
  ccapi.org.example.com:
    image: golang:1.18
    ports:
      - 80:80
    command: bash -c 'go run main.go'
    volumes:
      - ./:/rest-server
      - ../fabric/organizations:/fabric/organizations
    logging:
      options:
        max-size: 50m  
    environment:
      - SDK_PATH=./config/configsdk-org.yaml
      - USER=Admin
      - ORG=org
      - DOMAIN=example.com
      - CHANNEL=mainchannel
      - CCNAME=cc-tools-demo
      - FABRIC_GATEWAY_ENDPOINT=peer0.org.example.com:7051
      - FABRIC_GATEWAY_NAME=peer0.org.example.com
      - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn
    working_dir: /rest-server
    container_name: ccapi.org.example.com
    networks:
      - cc-tools-demo-net
