name: Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: chaincode
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21  

    - name: Build
      run: go build -v github.com/hyperledger-labs/cc-tools-demo/chaincode

    - name: Unit tests
      run: go test github.com/hyperledger-labs/cc-tools-demo/chaincode -coverpkg=./... -v
    
    # - name: Integration tests
    #   run: go test -v ./tests
